config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount Fakesite::Engine => "/fakesite" if Rails.env.development?

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  confirmations: "users/confirmations",
  unlocks: "users/unlocks"
  }

  root to: "hotels#index"

  resources :users, only: [ :index, :show, :destroy, :edit, :update ]
  resources :hotels, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :addresses, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  end

  resources :rooms, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]  do
    resources :comments
  end

    resources :reserve_rooms, only: [ :index, :show, :new, :create, :edit, :destroy ]  do
      resources :payments, only: [ :index, :show, :new, :create, :edit ]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :reserve_rooms
  before_save :set_code
  before_validation :set_number_of_room, on: :create
  before_save :status_check

  enum status: { available: 0, booked: 1 }
  enum room_type: { economic: 0, premium: 1, luxury: 2 }

  validates :status, inclusion: {  in: statuses.keys }
  validates :room_type, presence: true
  validates :code, length: { maximum: 6 }
  validates :hotel_id, presence: true
  validates :beds, presence: true
  validates :capacity, presence: true
  validates :price_per_night, presence: true
  validates :number_of_rooms, numericality: { only_integer: true, greater_than: 0 }

  def calculate_price(check_in_date, check_out_date)
    nights = (check_out_date - check_in_date).to_i
    @reserve_room.total_price = nights * price_per_night
  end

  def status_check
    self.status = "available" if status.nil?
  end

  def code_creation
    type_abbr = case room_type
    when "economic"
                    "ECO"
    when "premium"
                    "PRE"
    when "luxury"
                    "LUX"
    end
    "#{type_abbr}-#{number_of_rooms}"
  end

  def set_number_of_room
    if new_record?
      self.number_of_rooms = hotel.rooms.count + 1
    else
    hotel.rooms.each_with_index do |room, index|
      Rails.logger.debug "Setting number_of_rooms for Room ID #{room.id} to #{index + 1}"
      room.update(number_of_rooms: index + 1, code: room.code_creation)
      end
    end
  end

  private

  def available?
    status == "available"
  end

  def set_code
    self.code = code_creation if code.blank?
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [ :show, :edit, :update, :destroy ]
  before_action :set_user, only: [ :new, :edit, :create, :update ]
  before_action :authorize_admin, only: [ :new, :create, :edit, :update, :destroy ]
  load_and_authorize_resource

  # GET /rooms
  def index
    @rooms = Room.page(params[:page]).per(15)
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "No rooms found."
    redirect_to root_path
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST
  def create
    @room = Room.new(room_params)
    if @room.save
      @room.set_number_of_room
      @room.hotel.rooms.each(&:save)
      redirect_to @room, notice: "Room was successfully created."
    else
      flash[:alert] = "Creation failed. Please check the form for errors and try again."
      render :new
    end
  end

  # PUT
  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room was successfully updated."
    else
      flash[:alert] = "Update failed. Please check the form for errors and try again."
      render :edit
    end
  end

  # DELETE
  def destroy
    @room.destroy
    redirect_to rooms_path, notice: "Room was successfully destroyed."
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def set_hotel
  end

  def room_params
    params.require(:room).permit(
    :hotel_id,
    :room_type,
    :beds,
    :price_per_night,
    :capacity,
    :status,
    :created_at,
    :updated_at,
    { reserve_ids: [] })
  end

  def authorize_admin
    redirect_to(root_path, alert: "Access denied.") unless current_user.admin?
  end
end

app/helpers/room_helper.rb
module RoomHelper
  def current_room(room_id)
    Room.find_by(id: room_id) || (raise ActiveRecord::RecordNotFound, "Room not found")
  end

  def verify_room_status(room)
    if room.hotel.rooms.empty?
      flash[:alert] = "No rooms available for this hotel."
      redirect_to root_path and return
    end
  end

  def booked_room(room)
    room.update_column(:status, "booked")
  end

  def available_room(room)
    room.update_column(:status, "available")
  end
end

app/views/rooms/_form.html.erb
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= form_for(@room) do |room| %>
        <div class="row">
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :hotel_name %>
                    <%= room.select :hotel_id, options_from_collection_for_select(@user.hotels, :id, :name, @room.hotel_id), {}, class: "container-hotel-name" %>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :status %>
                    <%= room.select :status, Room.statuses.keys.map { |status| [status.humanize, status] }, { selected: @room.status }, class: "container-status" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :room_type %>
                    <%= room.select :room_type, Room.room_types.keys.map { |room_types| [room_types.humanize, room_types] }, { value: @room.room_type }, class: "container-room-type" %>
                </div>
                <div class="field">
                    <%= room.label :beds, "No.Beds" %>
                    <%= room.number_field :beds,  value: @room.beds  %>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :price_per_night, "Night Price" %>
                    <%= room.number_field :price_per_night,  value: @room.price_per_night  %>
                </div>
                <div class="field">
                    <%= room.label :capacity %>
                    <%= room.number_field :capacity,  value: @room.capacity %>
                </div>
            </div>
        </div>

        <div class="actions">
            <%= room.submit "Create" %>
        </div>
    <% end %>

app/views/rooms/_form_edit.html.erb
<div class="form">
    <%= form_for(@room) do |room| %>
        <div class="row">
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :hotel_name %>
                    <%= room.text_field :hotel_name, value: @room.hotel.name, readonly: true %>
                    <%= room.hidden_field :hotel_id, value: @room.hotel_id %>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :status %>
                    <%= room.select :status, Room.statuses.keys.map { |status| [status.humanize, status] }, { selected: @room.status }, class: "container-status" %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :room_type %>
                    <%= room.select :room_type, Room.room_types.keys.map { |room_types| [room_types.humanize, room_types] }, { value: @room.room_type }, class: "container-room-type" %>
                </div>
                <div class="field">
                    <%= room.label :beds, "No.Beds" %>
                    <%= room.number_field :beds,  value: @room.beds  %>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field">
                    <%= room.label :price_per_night, "Night Price" %>
                    <%= room.number_field :price_per_night,  value: @room.price_per_night  %>
                </div>
                <div class="field">
                    <%= room.label :capacity %>
                    <%= room.number_field :capacity,  value: @room.capacity %>
                </div>
            </div>
        </div>

        <div class="actions">
            <%= room.submit "Update" %>
        </div>
    <% end %>
</div>

app/views/rooms/_table.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2">Hotel</th>
            <th>Room</th>
            <th>Type</th>
            <th>Capacity</th>
            <th>Beds</th>
            <th>Price</th>
            <th>Status</th>
            <th>No.Reservations</th>
            <th>No.Comments</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @rooms.sort_by { |room| room.hotel.name }.each do |room| %>
            <td><%= room.hotel.name %></td>
            <td class="td-update"> 
                <%= link_to edit_hotel_path(room.hotel), class: 'update' do %>
                    <i class="bi bi-pencil-fill"></i>
                <% end %>
            </td>
            <td><%= room.code %></td>
            <td><%= room.room_type.capitalize %></td>
            <td><%= room.capacity %></td>
            <td><%= room.beds %></td>
            <td><%= room.price_per_night %></td>
            <td><%= room.status ? 'Booked' : 'Available' %></td>
            <td> </td>
            <td> </td>
            <td class="td-update"> 
                <%= link_to edit_room_path(room), class: 'update' do %>
                    <i class="bi bi-pencil-fill"></i>
                <% end %>
            </td>
            <td class="td-destroy"> 
                <%= link_to room_path(room), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: 'destroy' do%>
                    <i class="bi bi-trash3-fill"></i>
                <% end %>
            </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/rooms/edit.html.erb
<section class="sec-edit-rooms">
    <div class="main-title">
        <h2>Update Room <%= @room.code %></h2>
    </div>

    <div class="form-container">
        <% if flash[:alert] %>
            <div class="alert alert-danger">
                <%= flash[:alert] %>
            </div>
        <% end %>

        <%= render 'form_edit', room: @room %>
    </div>
</section>

app/views/rooms/index.html.erb
<section class="sec-list-rooms">
  <div class="main-title">
    <h2>My Hotels</h2>
  </div>
    <div class="form-container">
            <div class="pages">
                <%= paginate @rooms %>
            </div>
            <%= render  'rooms/table', locals: { rooms: @rooms } %>
        </div>
    <div class="row">
      <div class="col-md-6">
        <div class="actions">
          <%= link_to 'Create Hotel', new_hotel_path, class: 'btn' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="actions">
          <%= link_to 'Create Room', new_room_path, class: 'btn' %>
        </div>
      </div>
    </div>
</section>

app/views/rooms/new.html.erb
<section class="sec-create-rooms">
  <div class="main-title">
    <h2>Create Rooms</h2>
  </div>

  <div class="form-container">
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= render 'form', room: @room %>
  </div>
</section>