config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount Fakesite::Engine => "/fakesite" if Rails.env.development?

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  confirmations: "users/confirmations",
  unlocks: "users/unlocks"
  }

  root to: "hotels#index"

  resources :users, only: [ :index, :show, :destroy, :edit, :update ]
  resources :hotels, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :addresses, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  end

  resources :rooms, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]  do
    resources :comments
  end

    resources :reserve_rooms, only: [ :index, :show, :new, :create, :edit, :destroy ]  do
      resources :payments, only: [ :index, :show, :new, :create, :edit ]
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :user
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  before_validation :set_default_rating, on: :create
  has_many :rooms, dependent: :destroy
  has_many :reservations, through: :rooms, dependent: :destroy
  has_many :comments, through: :rooms, dependent: :destroy
  has_many_attached :images

  validates :name, presence: true,
  length: { minimum: 10, maximum: 100 }
  validates :phone, presence: true,
  format: { with: /\A[+\d]?(?:[\d\-.\s]{7,}\z)/,
  message: "must be a valid phone number" }
  validates :email, presence: true,
    format: { with: URI::MailTo::EMAIL_REGEXP,
    message: "must be a valid phone number" }
  validates :description, presence: true,
  length: { minimum: 10, maximum: 600 }
  validates :user_id, presence: true
  validates :rooms_ids, presence: false
  validates :rating, presence: false,  numericality: { greater_than_or_equal_to: 0,
   less_than_or_equal_to: 5 }

  def calculate_rating
    total_comments = comments.count
    total_rate = comments.sum(:rate)
    return 0 if total_comments.zero?

    average_rate = total_rate / total_comments.to_f

    self.rating = [ [ average_rate, 0 ].max, 5 ].min.round(2)
    save
  end

  private
  def set_default_rating
    self.rating ||= 0
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]
  before_action :set_hotel, only: %i[ edit update destroy]
  load_and_authorize_resource

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.includes(:address, images_attachments: :blob)
                   .page(params[:page])
                   .per(2)
    @address = Address.all
  rescue @hotels.empty?
    flash[:alert] = "No hotels found."
  end

  # GET /hotels/1 or /hotels/1.json
  def show
    @hotel = Hotel.includes(:address, images_attachments: :blob)
                  .find(params[:id])

    @economic_rooms = @hotel.rooms.where(room_type: "Economic")
    @premium_rooms = @hotel.rooms.where(room_type: "Premium")
    @luxury_rooms = @hotel.rooms.where(room_type: "Luxury")

    @check_in_date = params[:check_in_date]
    @check_out_date = params[:check_out_date]

    @grouped_rooms = @hotel.rooms.group_by(&:room_type).transform_values do |rooms|
      Kaminari.paginate_array(rooms).page(params[:page]).per(3)
    end
    @room = @hotel.rooms.first
    @room_type = @room.room_type if @room

    @min_price = @hotel.rooms.minimum(:price_per_night)
    @max_price = @hotel.rooms.maximum(:price_per_night)

    available_rooms = @hotel.rooms.where(status: "available")
    if available_rooms.exists? && @check_in_date.present? && @check_out_date.present?
      redirect_to new_reserve_room_path(hotel_id: @hotel.id, check_in_date: @check_in_date, check_out_date: @check_out_date)
    else
      flash.now[:alert] = "Please provide both check-in and check-out dates."
      render :show
    end
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Hotel not found."
    redirect_to hotels_path
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
    @hotel.build_address
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST
  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user = current_user
    if @hotel.save
      redirect_to @hotel, notice: "Hotel was successfully created."
    else
      flash.now[:alert] = @hotel.errors.full_messages.to_sentence
      render :new
    end
  end

  # PUT
  def update
    if @hotel.update(hotel_params)
      redirect_to @hotel, notice: "Hotel was successfully updated."
    else
      Rails.logger.debug @hotel.errors.full_messages.to_sentence
      flash[:alert] = "Update failed. Please check the form for errors and try again."
      render :edit
    end
  end

  # DELETE
  def destroy
    @hotel.destroy
    redirect_to hotels_path
  end

private

  def set_hotel
    @hotel = Hotel.find(params[:id])
    @address = @hotel.address
  end

  def hotel_params
    params.require(:hotel).permit(
      :name,
      :phone,
      :email,
      :description,
      :user_id,
      :address_id,
      :created_at,
      :updated_at,
      { room_ids: [] },
      :rating,
      { images: [] },
      address_attributes: [ :country,
      :city, :place_name ]
    )
  end

  def address_params
    params.require(:address).permit(:city,
    :place_name, :country)
  end
end

app/helpers/hotel_helper.rb
module HotelHelper
  def current_hotel
    @hotel ||= Hotel.first
  end

  def search_hotel(hotel_id)
    @hotel ||= Hotel.find(hotel_id)
  end
end

app/views/hotels/_card_sel_room.html.erb
<div class="date-selection-form">
    <%= form_with(model: @reserve_room, local: true) do |form| %>
        <div class="row">
            <div class="col">
                <div class="field">
                    <%= form.label :check_in_date %>
                    <%= form.date_field :check_in_date, value: (Date.today + 5.days).strftime("%Y-%m-%d"), class: "custom-date-field" %>
                </div>
            </div>
            <div class="col">
                <div class="field">
                    <%= form.label :check_out_date %>
                    <%= form.date_field :check_out_date, value: (Date.today + 5.days).strftime("%Y-%m-%d"), class: "custom-date-field" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="container-rooms">
    <% grouped_rooms.each do |room_type, rooms| %>
        <div class="column">
            <div class="title-col">
                <h2><%= room_type %></h2>
            </div> 
            <% rooms.each do |room| %>
            <div class="col">
                <div class="card mb-1">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <h3 class="card-title"><%= room.code %></h3>
                            </div>                                                  
                            <div class="col-md-6">
                                <div class="field">
                                    <strong>Price:</strong>
                                    <p class="card-text"><%= room.price_per_night %></p>
                                </div>
                                <div class="field">
                                    <strong>Capacity:</strong>
                                    <p class="card-text"><%= room.capacity %></p>
                                </div>
                                <div class="field">
                                    <strong>Beds:</strong>
                                    <p class="card-text"><%= room.beds %></p>
                                </div>
                            </div>
                            <div class="col-md-6 check">
                                <div class="form-check">
                                    <%= link_to 'Select', new_reserve_room_path(room_id: room.id, check_in_date: params[:reserve_room]&.dig(:check_in_date), check_out_date: params[:reserve_room]&.dig(:check_out_date)), class: 'btn' %>                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
            <div class="pages-rooms">
                <%= paginate rooms %>
            </div>
        </div>
    <% end %>
</div>

app/views/hotels/_form.html.erb
<%= form_with(model: @hotel, local: true, html: { multipart: true }) do |form| %>
    <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>
      <ul>
        <% @hotel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
        <div class="col-md-6">
            <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name %>
            </div>
            <div class="field">
                <%= form.label :phone %>
                <%= form.text_field :phone %>
            </div>
            <div class="field">
                <%= form.label :email %>
                <%= form.text_field :email %>
            </div>
        </div>
        <div class="col-md-6">
        <div class="container-address">
            <%= form.fields_for :address do |address_form| %>
                <%= render 'address/form', form: address_form %>
            <% end %>
        </div>
    </div>
</div>
    <div class="field-description">
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>

    <div class="first-image-field" id="image-fields">
        <%= form.label :images %>
        <div class="field">
            <%= form.file_field :images, multiple: true, class: "img-select" %>
        </div>
    </div>

    <div class="add-btn">
        <button type="button" onclick="addImageField()">
            <i class="bi bi-plus-circle-fill"></i>
        </button>
    </div>
        <script>
            function addImageField() {
                var imageFields = document.getElementById("image-fields");
                var imageFieldCount = imageFields.getElementsByClassName("field").length;
                if (imageFieldCount < 3) {
                    var newImageField = document.createElement("div");
                    newImageField.className = "field";
                    newImageField.innerHTML = `
                            <input type="file" name="hotel[images][]" class="img-select">
                            <button type="button" onclick="deleteImageField(this)">
                                <i class="bi bi-dash-circle-fill"></i>
                            </button>
                    `;
                    imageFields.appendChild(newImageField);
                } else {
                    alert("You can only upload a maximum of 3 images.");
                }
            }

            function deleteImageField(button) {
                var imageField = button.parentNode;
                imageField.parentNode.removeChild(imageField);
            }
        </script>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/hotels/_form_edit.html.erb
<%= form_with(model: @hotels, local: true) do |form| %>
    <div class="row">
        <div class="col-md-6">
            <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name, value: @hotel.name %>
            </div>
            <div class="field">
                <%= form.label :phone %>
                <%= form.text_field :phone, value: @hotel.phone %>
            </div>
            <div class="field">
                <%= form.label :email %>
                <%= form.text_field :email, value: @hotel.email %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="container-address">
                <%= form.fields_for :address do |address_form| %>
                    <%= render 'address/form', form: address_form %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="field-description">
        <%= form.label :description %>
        <%= form.text_area :description, value: @hotel.description %>
    </div>

   <div class="first-image-field" id="image-fields">
    <%= form.label :images %>
        <% @hotel.images.each_with_index do |image, index| %>
            <div class="field">
            <%= form.hidden_field :images_cache, value: rails_blob_url(image, only_path: true) %>
            <%= form.file_field :images,multiple: true, class: "img-select", data: { direct_upload: true } %>
            <button class="btn-current"><%= link_to 'Current', rails_blob_url(image, only_path: true)%></button>
            <button type="button" onclick="deleteImageField(this)">
                <i class="bi bi-dash-circle-fill"></i>
            </button>
            </div>
    <% end %>
    </div>

    <div class="add-btn">
        <button type="button" onclick="addImageField()">
            <i class="bi bi-plus-circle-fill"></i>
        </button>
    </div>

    <script>
        function addImageField() {
            var imageFields = document.getElementById("image-fields");
            var imageFieldCount = imageFields.getElementsByClassName("field").length;
            if (imageFieldCount < 3) {
                var newImageField = document.createElement("div");
                newImageField.className = "field";
                newImageField.innerHTML = `
                    <input type="file" name="hotel[images][]" class="img-select">
                    <button type="button" onclick="deleteImageField(this)">
                        <i class="bi bi-dash-circle-fill"></i>
                    </button>
                `;
                imageFields.appendChild(newImageField);
            } else {
                alert("You can only upload a maximum of 3 images.");
            }
        }

        function deleteImageField(button) {
            var imageField = button.parentNode;
            imageField.parentNode.removeChild(imageField);
        }
    </script>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/hotels/edit.html.erb
<section class="sec-edit-hotels">
    <div class="main-title">
        <h2>Update <%= @hotel.name %> Hotel</h2>
    </div>

    <div class="form-container">
        <%= render 'form_edit', hotel: @hotel %>
    </div>
</section>

app/views/hotels/index.html.erb
<section class="sec-catalog">
    <div class="main-title">
        <h2>Hotels Catalog</h2>
    </div>

    <div class="hotels-container">
        <div class="pages-hotels">
            <%= paginate @hotels %>
        </div>
        <% @hotels.each do |hotel| %>
            <div class="card">
                <div class="row">
                    <div class="col-md-6 info">
                        <div class="card-body">
                            <h5 class="card-title"><%= hotel.name %></h5>
                            <div class="contact-info">
                                <p class= "card-text"><%= hotel.phone%></p>
                                <p class= "card-text"><%= hotel.email%></p>
                            </div>
                            <div class="container-with-label">
                                <label>Address :</label>
                                <p class="card-text"><%= hotel.address.compound_address %>
                            </div>

                            <div class="container-with-label">
                                <label>About :</label>
                                <p class="card-text"><%= hotel.description %></p>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="container">
                                        <label>Rate :</label>
                                        <p class="card-text"><%= hotel.rating %></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="container">
                                        <label>Rooms :</label>
                                        <p class="card-text"><%= hotel.rooms.count %></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="container">
                                        <label>Night Price :</label>
                                        <p class="card-text">$ <%= hotel.rooms.minimum(:price_per_night).to_i %> - $ <%= hotel.rooms.maximum(:price_per_night).to_i %></p>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 reserve">
                                        <%= link_to 'Reserve', hotel_path(hotel.id), class: 'btn' %>
                                </div>
                            </div>                    
                        
                        </div>
                    </div>
                    <div class="col-md-6 image">
                        <div id="carouselExample<%= hotel.id %>" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                <% hotel.images.limit(3).each_with_index do |image, index| %>
                                    <div class="carousel-item <%= 'active' if index == 0 %>">
                                        <%= image_tag image %>
                                    </div>
                                <% end %>
                            </div>
                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample<%= hotel.id %>" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carouselExample<%= hotel.id %>" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                </button>
                        </div>
                    </div>
                </div> 
            </div>
        <% end %>
    </div>
</section>

app/views/hotels/new.html.erb
<section class="sec-create-hotel">
  <div class="main-title">
    <h2>Create Hotel</h2>
  </div>

  <div class="form-container">
    <%= render 'form', hotel: @hotel %>
  </div>
</section>

app/views/hotels/show.html.erb
<section class="sec-select-room">
    <div class="main-title">
        <h2><%= @hotel.name %></h2>
    </div>
    <div class="hotel-details">
        <div class="row">
            <div class="col-md-6">
                <div class="field">
                    <strong>Phone:</strong>
                    <p><%= @hotel.phone %></p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field">
                    <strong>Address:</strong>
                    <p><%= @hotel.address.compound_address %></p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="field">
                    <strong>Email:</strong>
                    <p><%= @hotel.email %></p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <hr class="divider">
    </div>

    <div class="form-container">   
        <div class="reservation-instructions">
            <p class="sel-title">Select both dates and a room, by clicking on "Select" button</p> 
            <%= form_with url: reserve_room_path, method: :post do |form| %>
                <%= render partial: 'card_sel_room', locals: { hotel_rooms: @hotel.rooms, room_type: @room_type, grouped_rooms: @grouped_rooms } %>
            <% end %>
        </div>          
    </div>
    <div class="row">
        <hr class="divider">
    </div> 
</section>