config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount Fakesite::Engine => "/fakesite" if Rails.env.development?

  devise_for :users, controllers: {
  sessions: "users/sessions",
  registrations: "users/registrations",
  passwords: "users/passwords",
  confirmations: "users/confirmations",
  unlocks: "users/unlocks"
  }

  root to: "hotels#index"

  resources :users, only: [ :index, :show, :destroy, :edit, :update ]
  resources :hotels, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :addresses, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  end

  resources :rooms, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]  do
    resources :comments
  end

    resources :reserve_rooms, only: [ :index, :show, :new, :create, :edit, :destroy ]  do
      resources :payments, only: [ :index, :show, :new, :create, :edit ]
  end
end

app/views/layouts/_footer.html.erb
<!--<footer>
      <p>&copy; <%= Time.now.year %> The Fine Gem. All rights reserved.</p>
    </footer> -->    

app/views/layouts/_nav-bar.html.erb
    <% resource_name = :user %>
    <% resource = User.new %>
    <% devise_mapping = Devise.mappings[:user] %>

    <nav>
        <div class="column links">
            <ul>
                <li class="first-links">
                    <a class="link-nav" href="/">
                    <i class="bi bi-gem"></i>
                    </a>
                <% if user_signed_in? %>
                    <% if current_user.client?%>
                        <li class="dropdown">
                            <a class="link-nav" href="/hotels" aria-expanded="false">
                                Hotels
                            </a>
                        </li>
                    <% else%>
                        <li class="dropdown">
                            <%= link_to 'Users', users_path, class: 'link-nav', aria: { expanded: false } %>
                        </li> 
                        <li class="dropdown">
                             <%= link_to 'Hotels', hotels_path, class: 'link-nav', aria: { expanded: false } %>
                        </li> 
                        <li class="dropdown">
                             <%= link_to 'My Hotel', rooms_path, class: 'link-nav', aria: { expanded: false } %>
                        </li> 
                        <li class="dropdown">
                            <%= link_to 'Reservations', reserve_rooms_path, class: 'link-nav', aria: { expanded: false } %>
                        </li>
                    <% end %>
                <% else %>

                <% end %>  
            </ul> 
        </div>
        <div class="column log-btns">
            <% if user_signed_in? %>
                <div class="btn-container">
                    <div class="container-fluid">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">                    
                                <i class="bi bi-person-circle"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <span class="ms-2"><%= current_user.full_name %></span>
                                <li><%= link_to 'Profile', edit_registration_path(current_user), class: 'nav-link' %></li>
                                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
                            </ul>
                        </div>
                    </div>
                </div>
            <% else %>
                <div class="btn-container">
                    <% if request.path == new_session_path(resource_name) %>
                        <div class="btn-sign-up">
                            <%= link_to 'Sign Up', new_registration_path(resource_name), class: 'btn' %>
                        </div>
                    <% elsif request.path == new_registration_path(resource_name) || request.path == user_registration_path %>
                        <div class="btn-sign-in">
                            <%= link_to 'Sign In', new_session_path(resource_name), class: 'btn' %>
                        </div>    
                    <% else %>
                        <div class="btn-sign-up">
                            <%= link_to 'Sign Up', new_registration_path(resource_name), class: 'btn' %>
                        </div> 
                        <div class="btn-sign-in">
                            <%= link_to 'Sign In', new_session_path(resource_name), class: 'btn' %>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "The Fine Gem" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/public/icon.png" type="image/png">
    <link rel="icon" href="/public/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&family=Roboto+Flex:opsz,wght@8..144,100..1000&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
       <%= render 'layouts/nav-bar' %>
    </header>
   
    <div class="flash-messages">
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </body>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</html>